# Generated by Django 4.1.4 on 2022-12-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adblock',
            field=models.BooleanField(default=False),
        ),
    ]
