# Generated by Django 4.1.5 on 2023-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_adblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ProfileDict',
            field=models.IntegerField(default=0),
        ),
    ]
